//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Phone Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PhoneInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PhoneInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Phone Inputs"",
    ""maps"": [
        {
            ""name"": ""Gyro"",
            ""id"": ""4758b664-9d4b-4c5f-8e11-11e117c9e7a6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""c771b205-0535-4214-a91f-6a9d6e084063"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f72707a4-3d69-4410-8ded-90fe959e966b"",
                    ""path"": ""<GravitySensor>/gravity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gyro"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gyro"",
            ""bindingGroup"": ""Gyro"",
            ""devices"": []
        }
    ]
}");
        // Gyro
        m_Gyro = asset.FindActionMap("Gyro", throwIfNotFound: true);
        m_Gyro_Move = m_Gyro.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gyro
    private readonly InputActionMap m_Gyro;
    private List<IGyroActions> m_GyroActionsCallbackInterfaces = new List<IGyroActions>();
    private readonly InputAction m_Gyro_Move;
    public struct GyroActions
    {
        private @PhoneInputs m_Wrapper;
        public GyroActions(@PhoneInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gyro_Move;
        public InputActionMap Get() { return m_Wrapper.m_Gyro; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GyroActions set) { return set.Get(); }
        public void AddCallbacks(IGyroActions instance)
        {
            if (instance == null || m_Wrapper.m_GyroActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GyroActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IGyroActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IGyroActions instance)
        {
            if (m_Wrapper.m_GyroActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGyroActions instance)
        {
            foreach (var item in m_Wrapper.m_GyroActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GyroActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GyroActions @Gyro => new GyroActions(this);
    private int m_GyroSchemeIndex = -1;
    public InputControlScheme GyroScheme
    {
        get
        {
            if (m_GyroSchemeIndex == -1) m_GyroSchemeIndex = asset.FindControlSchemeIndex("Gyro");
            return asset.controlSchemes[m_GyroSchemeIndex];
        }
    }
    public interface IGyroActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
